姓名：每日新闻推送

在……之上:
计划表:
-克朗：'00，8，16***'
工作流程分派(_D)：

工作:
跑-网上机器人:
跑步次数-on:ubuntu-latest
步骤:
-姓名：获取代码
用途：操作/签出@V4
-姓名：安装python
用法：操作/设置-python@V5
和……一起:
          python-版本：'3.10'
-姓名：安装依赖
运行：PIP安装请求
-姓名：运行新闻机器人
        env:
Tian_API_KEY：${{秘密.Tian_API_KEY}}
Webhook_URL：${{秘密.Webhook_URL}}
运行：pythonnews_bot。py
